spring:
  # 数据源，连接MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/sp_mb_vue?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # thymeleaf模板引擎配置，设置编码，false取消缓存
  thymeleaf:
    encoding: UTF-8
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
mvc:
  static-path-pattern: /upload/**
server:
  # 修改启动端口号
  port: 1205
  # 静态资源映射路径
  web:
    resources:
      static-locations: classpath:/static/
